
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Fall back to the bundled demo db so `prisma generate` (which loads this
// config) doesn't hard-fail on Vercel, where DATABASE_URL isn't set — the
// actual app never reads this value, see src/lib/prisma.ts.
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: process.env.DATABASE_URL ?? "file:./prisma/seed-data.db",
  },
});
